### ISSUE TITLE
Having trouble running substrata on my mac

### ISSUE THREAD

**Issue by JerryBerry12** [glaretechnologies/substrata#3]
Hi,
Sorry, I'm back again. The PC is working fine, but when I try to run it on my mac, it doesn't even show a window. The icon just bounces a couple times, then sends an error message. Sometimes I see the help information window, but nothing else. It has nothing to do with downloading stuff from the server, bc I tried disconnecting wifi and doing the same thing, and it quit exactly the same way.
The message is attached below.
Specs: MacBook Pro Retina 13 inch (Late 2012)
CPU: 2.5 GHz Dual-Core Intel Core i5 
RAM: 8GB
Graphics: Intel HD Graphics 4000 1536 MB
Mac OS: 10.15 (Catalina)
Thanks!

[error substrata.txt](https://github.com/user-attachments/files/15513319/error.substrata.txt)

**Comment by Ono-Sendai** [comment]
Your mac is probably too old and with too shitty opengl drivers to work with substrata, sorry.
Blame apple.
